#pragma once
#include <iostream>
#include <algorithm>
#include <glad/glad.h>
#include <SDL.h>
#include "FONT/SDL_ttf.h"
#include <vector>
#include <string>
#include <filesystem>
#include <limits.h>
#include <zip.h>
#include <fstream>
#include <stdio.h>
#include "steam/steam_api.h"
#include <Themida/ThemidaSDK.h>
#include <msgpack.hpp>
#include <openssl/opensslconf.h>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/engine.h>
#include <websocketpp/config/asio_client.hpp>
#include <websocketpp/client.hpp>
#include <stdlib.h>
#include <SDL_image.h>
#include <regex>
#include <SDL_sound.h>
#include <bass.h>
#include <curl/curl.h>
#include <sstream>
#include <string>
#include <fstream>
#include <filesystem>

#include "Packet.h"
#include "SPacketUpdateLeaderboard.h"
#include "SPacketFinalizeChart.h"
#include "CPacketSongFinished.h"
#include "CPacketNoteHit.h"
#include "SPacketUpdateLobbyData.h"
#include "SPacketWtfAmInReply.h"
#include "CPacketWtfAmIn.h"
#include "CPacketLeave.h"
#include "SPacketStartLobbyGame.h"
#include "SPacketUpdateLobbyChart.h"
#include "CPacketChartAcquired.h"
#include "CPacketHostChangeChart.h"
#include "CPacketHostStartGame.h"
#include <io.h>